global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - 'alerting_rules.yml'


alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservices'
    static_configs:
      - targets:
        - 'auth:4000'
        - 'game:4000'
        - 'tournament:4000'
        - 'user:4000'
        - 'websocket:4000'
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  - job_name: 'filebeat-logstash'
    static_configs:
      - targets: ['telegraf:9273']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['es_exporter:9114']
    metrics_path: '/metrics'
