services:

  gateway:
    container_name: backend_gateway
    build: ./src/gateway
    networks:
      - backend
    volumes:
      - app_logs:/var/log/app
    depends_on:
      - auth
      - game
      - tournament
      - user
      - websocket
    restart: on-failure
    env_file:
      - .env
  
  auth:
    container_name: backend_auth
    build: ./src/auth
    networks:
      - backend
    volumes:
      - ./src/auth/data:/app/data
      - app_logs:/var/log/app
    restart: on-failure
    env_file:
      - .env
  
  game:
    container_name: backend_game
    build: ./src/game
    networks:
      - backend
    volumes:
      - ./src/game/data:/app/data
      - app_logs:/var/log/app
    restart: on-failure
    env_file:
      - .env
  
  tournament:
    container_name: backend_tournament
    build: ./src/tournament
    networks:
      - backend
    volumes:
      - ./src/tournament/data:/app/data
      - app_logs:/var/log/app
    restart: on-failure
    env_file:
      - .env

  user:
    container_name: backend_user
    build: ./src/user
    networks:
      - backend
    volumes:
      - ./src/user/data:/app/data
      - app_logs:/var/log/app
    restart: on-failure
    env_file:
      - .env

  websocket:
    container_name: backend_websocket
    build: ./src/websocket  
    networks:
      - backend
    volumes:
      - ./src/websocket/data:/app/data
      - app_logs:/var/log/app
    restart: on-failure
    env_file:
      - .env


