filebeat.inputs:
  - type: filestream
    enabled: true
    id: trans-input
    paths:
      - /var/log/app/*-service.log
      - /var/log/app/*-service-error.log
    fields:
      log_type: application
      service_type: microservice
      collection_method: volume
    fields_under_root: true

output.logstash:
  hosts: ${LOGSTASH_HOSTS}
  ssl.enabled: true
  ssl.certificate_authorities: ${CA_CERT}
  ssl.certificate: ${SSL_CERTIFICATE}
  ssl.key: ${SSL_KEY}

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: ${CA_CERT}

logging.level: debug
logging.to_stderr: true
#logging.to_files: true
#logging.files:
  #path: /var/log/filebeat
  #name: filebeat
  #keepfiles: 7
  #permissions: 0644

#queue.mem:
  #events: 4096
  #bulk_max_size: 512
  #flush.timeout: 1s

#max_procs: 1
#


# ############################# #
# DEBUG MINAL FUCNTIONAL LAUNCH #
# ############################# #

#filebeat.inputs:
#- type: filestream
  #enabled: true
  ##paths:
    #- /var/log/app/*.log

#output.console:
  #pretty: true

#logging.level: info
#logging.to_stderr: true
