{
 "title": "Ingest Pipeline (Filebeat Logstash)",
 "tags": [
  "logstash",
  "filebat"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Telegraf Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Telegraf Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(internal_agent_gather_errors)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"filebeat-logstash\"}",
     "legendFormat": "Heap Usage"
    }
   ]
  },
  {
   "title": "Failed Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(internal_agent_metrics_rejected{job=\"filebeat-logstash\"})",
     "legendFormat": "Metrics Collect Failed"
    },
    {
     "expr": "sum(internal_agent_metrics_dropped{job=\"filebeat-logstash\"})",
     "legendFormat": "Metrecs Export Failed"
    }
   ]
  },
  { "title": "Filebeat Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Filebat Ingested Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(beat_filebeat_events_active[5m])",
     "legendFormat": "Events Active"
    },
    {
     "expr": "rate(beat_filebeat_events_added[5m])",
     "legendFormat": "Events Added"
    },
    {
     "expr": "rate(beat_filebeat_events_done[5m])",
     "legendFormat": "Events Done"
    }
   ]
  },
  {
   "title": "Active Harvesters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "beat_filebeat_harvester_running",
     "legendFormat": "Active Harvester"
    },
    {
     "expr": "beat_filebeat_harvester_started",
     "legendFormat": "Started Harvester"
    },
    { "expr": "beat_filebeat_harvester_closed", "legendFormat": "Closed Harvester" }
   ]
  },
  { "title": "Logstash Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "I/O Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "rate(logstash_events_in[5m])", "legendFormat": "Events In" },
    { "expr": "rate(logstash_events_out[5m])", "legendFormat": "Events Out" }
   ]
  },
  {
   "title": "Top 5 Slower Plugins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, logstash_plugins_duration_in_millis)",
     "legendFormat": "{{plugin_type}} : {{plugin_name}}"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(logstash_events_duration_in_millis)",
     "legendFormat": "Event duration"
    }
   ]
  },
  {
   "title": "Active Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "logstash_jvm_threads_count / logstash_jvm_threads_peak_count",
     "legendFormat": "Active Threads / Pics"
    }
   ]
  },
  {
   "title": "Logstash Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(logstash_jvm_mem_heap_used_percent)",
     "legendFormat": "Avg percent"
    }
   ]
  }
 ]
}