{
 "title": "Architecture Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (job)",
     "legendFormat": "Total Rquest per Seconds"
    }
   ]
  },
  {
   "title": "Average Latence",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Latency Services",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (instance) (rate(http_request_duration_seconds_sum[5m])) \n  / \n  sum by (instance) (rate(http_request_duration_seconds_count[5m]))\n) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Percent by serrive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code!=\"200\"}[5m])) by (instance) / sum(rate(http_request_duration_seconds_count[5m])) by (instance) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}