services:

  

  prometheus:
    container_name: monitor_prometheus
    networks:
      - monitoring
      - backend
    build:
      context: ./src/prometheus
      args:
        PROM_PASSWORD_HASH: ${PROM_PASSWORD_HASH}
    volumes:
      - prometheus-data:/prometheus
    environment:
      - PROM_PASSWORD_HASH=${PROM_PASSWORD_HASH}
    ports:
      - "9090:9090" # <- Close it when grafana is set
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=1GB'
    restart: unless-stopped

  alertmanager:
    container_name: monitor_alertmanager
    networks:
      - monitoring
    build:
      context: ./src/alertmanager
      args:
       DISCORD_HOOK_URL: ${DISCORD_HOOK_URL}
    ports:
      - "127.0.0.1:9093:9093" # <- Close when debug is over (just PORTS: 9093 should be ok)
    restart: unless-stopped

  #grafana:
    #container_name: monitor_grafana
    #network:
      #- monitoring
    #restart: unless-stopped

  cadvisor:
    container_name: monitor_cadvisor
    networks:
      - monitoring
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    restart: unless-stopped

  es_exporter:
    container_name: monitor_es_exporter
    networks:
      - monitoring
      - elk
    depends_on:
      es01:
        condition: service_healthy
    image: prometheuscommunity/elasticsearch-exporter:v1.9.0
    volumes:
      - certs:/certs:ro
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    command:
      - '--es.uri=https://elastic:${ELASTIC_PASSWORD}@es01:9200'
      - '--es.ca=/certs/ca/ca.crt'
    expose:
      - 9114
    restart: unless-stopped

  telegraf:
    container_name: monitor_telegraf
    networks:
      - monitoring
      - elk
    depends_on:
      logstash:
        condition: service_healthy
      filebeat:
        condition: service_started
    image: telegraf:1.36.2
    volumes:
      - ./src/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

