services:

  prometheus:
    container_name: monitor_prometheus
    networks:
      - monitoring
      - backend
    build:
      context: ./src/prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  alertmanager:
    container_name: monitor_alertmanager
    networks:
      - monitoring
    build:
      context: ./src/alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    environment:
      - DISCORD_HOOK_URL=${DISCORD_HOOK_URL}
    restart: unless-stopped




  #grafana:
    #container_name: monitor_grafana
    #network:
      #- monitoring
    #restart: unless-stopped

  #cadvisor:
    #container_name: monitor_cadvisor
    #network:
      #- monitoring
    #restart: unless-stopped
