services:

  prometheus:
    container_name: monitor_prometheus
    networks:
      - monitoring
      - backend
      - elk
    build:
      context: ./src/prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=1GB'
    restart: unless-stopped

  alertmanager:
    container_name: monitor_alertmanager
    networks:
      - monitoring
    build:
      context: ./src/alertmanager
      args:
       DISCORD_HOOK_URL: ${DISCORD_HOOK_URL}
    ports:
      - "127.0.0.1:9093:9093"
    restart: unless-stopped

  #grafana:
    #container_name: monitor_grafana
    #network:
      #- monitoring
    #restart: unless-stopped

  #cadvisor:
    #container_name: monitor_cadvisor
    #network:
      #- monitoring
    #restart: unless-stopped

  es_exporter:
    container_name: monitor_es_exporter
    networks:
      - monitoring
      - elk
    depends_on:
      es01:
        condition: service_healthy
    image: prometheuscommunity/elasticsearch-exporter:v1.9.0
    volumes:
      - certs:/certs:ro
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    command:
      - '--es.uri=https://elastic:${ELASTIC_PASSWORD}@es01:9200'
      - '--es.ca=/certs/ca/ca.crt'
    expose:
      - 9114
    restart: unless-stopped

  #logstash_exporter:

  #kibana_exporter:

